apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices
spec:
  selector:
    matchLabels:
      app: microservices
  replicas: 1 
  template: 
    metadata:
      labels:
        app: microservices
    spec:
      containers:
      - name: microservices
        image: riyazshaik123/microservicesv1.0:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: microservces
spec:
  type: LoadBalancer
  selector:
    app: microservices
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
